FROM node:12.7.0-alpine

RUN apk update && \
    apk add --no-cache util-linux vim

RUN mkdir /app
WORKDIR /app

COPY ./package.json package.json
COPY ./package-lock.json package-lock.json

# ADD ../ /app

CMD npm install
