name: Task Manager

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.0

    - name: Setup project
      run: make setup

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: make test

    - name: Lint project
      run: make lint
